title: Lihua's Blog
author: Lihua Lan
description: 记录我的研究生学习旅程
baseurl: "/lihualan.github.io"
url: "https://AliLan.github.io"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
markdown: kramdown
minima:
  include_css:
    - /assets/css/custom.css